import pandas as pd

# Replace 'your_file.txt' with the actual filename
df = pd.read_csv('TUS106_L04 copy.TXT', header=None, usecols=[0])  # Read only first column

# Extract first 32 alphabets
df['Common_Id'] = df[0].str[:32]
df['Level'] = df[0].str[32:34]
df['Filler'] = df[0].str[34:36]
df['srl. No of member'] = df[0].str[36:39]
df['Age'] = df[0].str[39:42]
df['relationship of the informant with the household member '] = df[0].str[42:44]
df['day of week'] = df[0].str[44]
df['type of the day'] = df[0].str[45]
df['response code'] = df[0].str[46]
df['Blank'] = df[0].str[47:126]
df['NSC'] = df[0].str[126:129]
df['MULT'] = df[0].str[129:139]



# Save to a CSV file (drop original data column)
df.drop(columns=[0], inplace=True)  # Drop the first column (original data)
df.to_csv('File4.csv', index=False)

In [1]:
import pandas as pd

In [3]:

import pandas as pd

# Load the data into a pandas DataFrame
df = pd.read_csv('/Users/apoorvsingh/Downloads/TIME USE /Data Preprocessing/File4/File4.csv',low_memory=False)

# Create the "Person_ID" column
df['Person_ID'] = df['Common_Id'].astype(str) + '_' + df['srl. No of member'].astype(str)

# Display the updated DataFrame
# Save the updated DataFrame to a new CSV file
df.to_csv('updated_file.csv', index=False)

In [ ]:
df=pd.read_csv("File4.csv")

/var/folders/vn/qftdxjnd1j176qq200gvydx80000gn/T/ipykernel_69276/1256295249.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/Users/vjsuyash/Documents/UGP/Data Preprocessing/File4/File4.csv")

In [4]:
df['Person_ID'].nunique()

447250

In [5]:
df['Common_Id'].astype

<bound method NDFrame.astype of 0         TUS10202106201910111901311011001
1         TUS10202106201910111901311011001
2         TUS10202106201910111901311011002
3         TUS10202106201910111901311011002
4         TUS10202106201910111901311011002
                        ...
447245    TUS26082106201923612304043361013
447246    TUS26082106201923612304043361014
447247    TUS26082106201923612304043361014
447248    TUS26082106201923612304043361014
447249    TUS26082106201923612304043361014
Name: Common_Id, Length: 447250, dtype: object>

In [6]:
df['srl. No of member'].astype

<bound method NDFrame.astype of 0         1
1         2
2         1
3         2
4         4
         ..
447245    2
447246    1
447247    2
447248    3
447249    4
Name: srl. No of member, Length: 447250, dtype: int64>

In [9]:
df2 = pd.read_csv("/Users/apoorvsingh/Downloads/TIME USE /Apoorv/File5_Apoorv.csv",low_memory=False)

In [10]:
df2 = df2[df2['whether a major activity']==1]

In [11]:
df3 = (
    df2
    .groupby('Person_ID', as_index=False)
    .agg({'time in minute': 'sum'})
)

In [14]:
df['Person_ID'].unique()

array(['TUS10202106201910111901311011001_1',
       'TUS10202106201910111901311011001_2',
       'TUS10202106201910111901311011002_1', ...,
       'TUS26082106201923612304043361014_2',
       'TUS26082106201923612304043361014_3',
       'TUS26082106201923612304043361014_4'],
      shape=(447250,), dtype=object)

In [12]:
df3

                                 Person_ID  time in minute
0       TUS10001106201913310301382332001_1          1440.0
1       TUS10001106201913310301382332001_2          1440.0
2       TUS10001106201913310301382332001_3          1440.0
3       TUS10001106201913310301382332001_4          1440.0
4       TUS10001106201913310301382332002_1          1440.0
...                                    ...             ...
445294  TUS26124106201922831003013281014_1          1440.0
445295  TUS26124106201922831003013281014_2          1440.0
445296  TUS26124106201922831003013281014_3          1440.0
445297  TUS26124106201922831003013281014_4          1440.0
445298  TUS26124106201922831003013281014_5          1440.0

[445299 rows x 2 columns]

In [15]:
# Get Person_IDs present in df but not in df3
unique_person_ids = df.loc[~df['Person_ID'].isin(df3['Person_ID']), 'Person_ID'].unique()

# # If you also want the filtered dataframe (without common Person_IDs)
# df_unique = df[df['Person_ID'].isin(unique_person_ids)]

# print(df_unique)

In [ ]:
unique_person_id2s = df.loc[~df['Person_ID'].isin(df3['Person_ID']), 'Person_ID'].unique()

In [16]:
unique_person_ids

array(['TUS12469106201910130803342012002_4',
       'TUS12469106201910130803342012002_5',
       'TUS12469106201910130803342012002_6', ...,
       'TUS23085106201923612304074361010_3',
       'TUS24712106201923612304101361009_3',
       'TUS25440106201923612304042361003_4'], shape=(1955,), dtype=object)

In [31]:
df

,Common_Id,Level,Filler,srl. No of member,Age,relationship of the informant with the household member,day of week,type of the day,response code,Blank,NSC,MULT,Person_ID
0,TUS10202106201910111901311011001,4,00,1,44,02,1,1,1,...,4,1281550,TUS10202106201910111901311011001_1
1,TUS10202106201910111901311011001,4,00,2,32,01,1,1,1,...,4,1281550,TUS10202106201910111901311011001_2
2,TUS10202106201910111901311011002,4,00,1,38,01,5,1,1,...,4,1281550,TUS10202106201910111901311011002_1
3,TUS10202106201910111901311011002,4,00,2,32,01,5,1,1,...,4,1281550,TUS10202106201910111901311011002_2
4,TUS10202106201910111901311011002,4,00,4,7,02,5,1,1,...,4,1281550,TUS10202106201910111901311011002_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
447245,TUS26082106201923612304043361013,4,0,2,43,01,2,1,1,...,4,704688,TUS26082106201923612304043361013_2
447246,TUS26082106201923612304043361014,4,0,1,49,01,2,1,1,...,4,704688,TUS26082106201923612304043361014_1
447247,TUS26082106201923612304043361014,4,0,2,45,01,2,1,1,...,4,704688,TUS26082106201923612304043361014_2
447248,TUS26082106201923612304043361014,4,0,3,24,02,2,1,1,...,4,704688,TUS26082106201923612304043361014_3
447249,TUS26082106201923612304043361014,4,0,4,20,01,2,1,1,...,4,704688,TUS26082106201923612304043361014_4

In [32]:
df[df['Common_Id']=='TUS12469106201910130803342012002']['srl. No of member'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12])

In [29]:
df2[df2['Common_Id']=='TUS12469106201910130803342012002']['Serial no.of member'].unique()

array([ 1,  2,  3, 10, 11])

In [27]:
# Get Person_IDs present in df3 but not in df
unique_person_id2s = df3.loc[~df3['Person_ID'].isin(df['Person_ID']), 'Person_ID'].unique()

In [28]:
unique_person_id2s

array(['TUS10215106201910220502113021007_5',
       'TUS16727106201911420102313 MAN10_7',
       'TUS16727106201911420102313 MAN10_8',
       'TUS20964106201920621301023061210_5'], dtype=object)